### PR TITLE
Updated CLIView.printPlayerScores() to correctly sort the player rankings

### PR DESCRIPTION
**Pull request by nflanagan6**
When swapping the two player rankings being compared, I used the wrong variable at one point. Now corrected

### CODE REVIEW

**Comment by nflanagan6** [comment]
@abbiland  @Hunt-E @roym5 Can you all look this over please? 

Thanks

**Review by roym5 — COMMENTED** [review]
looks good

**Comment by Hunt-E** [comment]
I agree, looks good

**Comment by abbiland** [comment]
Looks good!

**Pull request merged**
