### PR TITLE
#41 scoring and initial hole functionality

### PR DESCRIPTION
**Pull request by nflanagan6**
Added functionality to get players' scores in Controller and print them in ascending order in CLIView

Also added GolfCard with getGolfValue() 

Included getters for the current hole and the total number of holes in View

### CODE REVIEW

**Comment by nflanagan6** [comment]
Hey @abbiland @Hunt-E @roym5, 

I've finished work on my story. Does this look ok to you all? 

Thanks

**Comment by Hunt-E** [comment]
In printPlayerScore in CLIView, printing the hole that the players are on would just be numberOfHolesPlayed++, because that is always one hole less than what they are on.
Also, the getPlayerScores method in Controller doesn't add up scores from the previous holes. The playerScores array should be implemented at the start of the code with the other variables. Also, playerScores[i] = playerScore should be +=, to take previous hole scores into account for the final score.
Other than that, everything else looks good, and making everything into a GolfCard allows us to change things and add methods to them easier to use for different games if we wanted, so good call.

**Comment by roym5** [comment]
Ethan pretty much covered it all, looks good.

**Comment by nflanagan6** [comment]
> In printPlayerScore in CLIView, printing the hole that the players are on would just be numberOfHolesPlayed++, because that is always one hole less than what they are on.
> Also, the getPlayerScores method in Controller doesn't add up scores from the previous holes. The playerScores array should be implemented at the start of the code with the other variables. Also, playerScores[i] = playerScore should be +=, to take previous hole scores into account for the final score.
> Other than that, everything else looks good, and making everything into a GolfCard allows us to change things and add methods to them easier to use for different games if we wanted, so good call.

Thanks @Hunt-E! I got that corrected

@roym5 @abbiland I can't remember whose story this is under, but playerScores in Controller will need to be updated when each hole ends. I'm sure you all already know that, but I wanted to double check.

**Pull request merged**
