### PR TITLE
Changes to run the code

### PR DESCRIPTION
**Pull request by Hunt-E**
Changes the code to have a new method print the end of each hole as well as changing formatting when running the game

### CODE REVIEW

**Review by roym5 — APPROVED** [review]
We had problems printing out the scores correctly and this looks to fix that in an efficient way. 
The new method added: printEndOfHole is well implemented.
The space created for the card game view works well in making the game more clear on whats happening.
Should be good.

**Review by nflanagan6 — CHANGES_REQUESTED** [review]
Hey @Hunt-E @abbiland @roym5, 

Everything @Hunt-E just added looks great, but I played through it and realized it doesn't tell you when a whole ends. I ended a hole as player 1, and it said "It's player 1's turn!" and showed me a completely new hand. This is kind of confusing, can whoever had the next hole story please add something letting the players know they're on the next hole? 

Thanks!
nflanagann6
Ending Hole Without Notification

**Review by roym5 — COMMENTED** [review]
This should solve what nathan was talking about

**Review by roym5 — COMMENTED** [review]
Added this here instead of a new PR for the test case

**Review by nflanagan6 — APPROVED** [review]
Looks good, thanks @Hunt-E

**Comment by abbiland** [comment]
This looks good, good fix to the issues we were having

**Pull request merged**
